### ISSUE TITLE
Results in a java.lang.NullPointerException when twitter.operation parameter is not specified

### ISSUE THREAD

**Issue by sameerak** [wso2-extensions/esb-inbound-twitter#7]
**Description:**
When twitter inbound endpoint is created without specifying a twitter.operation parameter, 
ERROR {org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter} - Error in executing task: null java.lang.NullPointerException
is continuously logged.

Instead of a NullPointerException, some helpful message may be displayed

**Suggested Labels:**
missing operation parameter

**Suggested Assignees:**

**Affected Product Version:**
org.apache.synapse.twitter.poll.class-1.0.0

**OS, DB, other environment details and versions:**    
Tested on ESB 4.9.0 and EI 6.6.0

**Steps to reproduce:**
Follow steps in [1] to add Twitter inbound enpoint to ESB, without specifying twitter.operation parameter.

[1] https://docs.wso2.com/display/ESBCONNECTORS/Configuring+Twitter+Inbound+Operations#ConfiguringTwitterInboundOperations-Properties

**Related Issues:**

**Comment by sameerak** [comment]
Sample update to resolve this issue is provided in pull request 8 [1].

[1] https://github.com/wso2-extensions/esb-inbound-twitter/pull/8

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3508
